### ISSUE TITLE
Using TinyDA optimiser with SeisSol

### ISSUE THREAD

**Issue by SrishtiDasgupta** [sebwolf-de/Seis-Bridge#2]
Hello, 

We are a team working with the Chair of Computer Architecture and Parallel Systems at TUM and BMW A.G. We have been using SeisSol and specifically Seis-Bridge as our workflow for investigating resource allocation for HPC applications. We were in contact with Sebastian Wolf regarding this project and collaboration between our Chairs. 

We have a question regarding use of TinyDA as an optimiser for SeisSol. To use seissol with TinyDA over UM-bridge, we need to specify a 'prior' and a 'likelihood', at least in terms of TinyDA. From the documentation and examples, we assume that these values might be some kind of distribution: gausssian or otherwise. Can you help us here in formulating the distribution, specifically for SeisSol ? We are using tpv13 in our workflows ?

Thanks

**Comment by vikaskurapati** [comment]
Hi,

I am closing this issue as I believe your queries were solved in our private conversations. Please write us another email if you need any more help.
